import { z } from "zod";

/**
 * HoroscopeResultSchema
 * Validates a single-day horoscope result generated by Gemini
 * This schema mirrors src/types/horoscope.types.ts
 */
export const HoroscopeResultSchema = z.object({
  quote: z.string().optional(),
  advice: z.string().optional(),
  affirmation: z.string().optional(),
  warning: z.string().optional(),
  release: z.string().optional(),

  do: z.array(z.string()).optional(),
  dont: z.array(z.string()).optional(),

  tarot: z.string().optional(),
  moon: z.string().optional(),
  transits: z.string().optional(),

  newLove: z.array(z.string()).optional(),
  luckyNumbers: z.array(z.string()).optional(),
});

/**
 * Inferred TypeScript type (optional helper)
 * Prefer importing the interface from src/types/horoscope.types.ts
 */
export type HoroscopeResultFromSchema = z.infer<typeof HoroscopeResultSchema>;
